name: Do things on PRs

on:
  pull_request:

jobs:

  validate:
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.base.ref }}
    steps:

      - name: Install pre-commit and dependencies
        run: |
          echo ${{ github.event.pull_request.base.ref }} #main -> target
          echo ${{ github.ref }} #refs/pull/1/merge
          echo ${{ github.head_ref }} #test -> source
          echo ${{ github.base_ref }} #main -> target
