name: "Test"

on:
  workflow_dispatch: # on manual trigger in github
    inputs:
      environment:
        description: "Choose an env to deploy to"
        required: true
        type: choice
        options:
          - dev
          - prd

permissions:
  contents: read    # This is required for actions/checkout
  id-token: write  

jobs:
  something:
    runs-on: ubuntu-latest
    environment: ${{ inputs.enviroment }}
    steps:
      - run: |
          echo "input: ${{ inputs.environment }}"
          echo "vars: ${{ vars.PRD_ONLY }}"
