name: Do things on PRs

on:
  pull_request:

jobs:

  validate:
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.base.ref }}
    steps:

      - name: Install pre-commit and dependencies
        run: |
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          
